typography_spectrum: 0.48687
color:
  brandColors:
    - '#3d898b'
    - '#503a2b'
    - '#efdda2'
    - '#e6983d'
    - '#b3a045'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.58531
analytics:
  google: null
  facebook: null
  twitter: null
name: James B Maxwell
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'James B. Maxwell: composer'
description: composer
purpose: []
