name: James B Maxwell
favicon: null
layout_spectrum: 0.07944002468138933
typography_spectrum: 0.48687
title: 'James B. Maxwell: composer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b3b3b'
    - '#9ea569'
    - '#bf4169'
    - '#894865'
    - '#c6d23d'
  brandStrength: 0.7966412217356265
  lightness: 0.375
  saturation: 0.9877318253275007
  rhythmicContrast: 0.5584993737284094
purpose: []
