name: James B Maxwell
favicon: null
layout_spectrum: 0.07944002468138933
typography_spectrum: 0.48687
title: 'James B. Maxwell: composer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d898b'
    - '#503a2b'
    - '#efdda2'
    - '#e6983d'
    - '#b3a045'
  brandStrength: 0.125
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
