name: James B Maxwell
favicon: null
layout_spectrum: 0.07944002468138933
typography_spectrum: 0.7398301190696657
title: 'James B. Maxwell: composer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7966412217356265
  lightness: 0.04196498286910355
  saturation: 0.9877318253275007
  rhythmicContrast: 0.5584993737284094
purpose: []
