name: James B Maxwell
favicon: null
layout_spectrum: 0.58531
typography_spectrum: 0.48687
title: James B. Maxwell
description: composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d898b'
    - '#503a2b'
    - '#efdda2'
    - '#e6983d'
    - '#b3a045'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
